name: Deploy BLDB-Count to VPS

on:
  push:
    branches:
      - main  # Löst den Workflow bei Push zum main-Branch aus
  workflow_dispatch: # Ermöglicht manuelles Starten

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add VPS to known_hosts
        run: ssh-keyscan -H ${{ secrets.VPS_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS using rsync
        env:
          VPS_USER_HOST: "${{ secrets.VPS_SSH_USER }}@${{ secrets.VPS_SSH_HOST }}"
          TARGET_DIR: ${{ secrets.VPS_TARGET_DIR }} # z.B. /var/www/bldb-count
        run: |
          echo "Starting deployment to ${{ env.VPS_USER_HOST }}"
          # Verwende rsync, um die Dateien zu synchronisieren.
          # --delete sorgt dafür, dass Dateien auf dem Server gelöscht werden, die nicht mehr im Repository sind.
          # Das .github-Verzeichnis und .git* werden ausgeschlossen.
          rsync -avz --delete \
            --exclude='.github/' \
            --exclude='.git/' \
            --exclude='.gitignore' \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ ${{ env.VPS_USER_HOST }}:${{ env.TARGET_DIR }}
          
          echo "Deployment successful!"